### ISSUE TITLE
Failed to activate the unregistered package

### ISSUE THREAD

**Issue by imcotton** [thiagopnts/unregistered#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [unregistered](https://github.com/thiagopnts/unregistered) package, v0.0.1

### Stack Trace

Failed to activate the unregistered package

```
At Cannot read property 'on' of undefined

TypeError: Cannot read property 'on' of undefined
    at Object.module.exports.activate (/Users/foobar/.atom/packages/unregistered/lib/unregistered.coffee:6:32)
    at Package.module.exports.Package.activateNow (/Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/foobar/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.10
unregistered, v0.0.1
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by thiagopnts** [comment]
I guess Atom changed its API on 1.0, gonna check this later.
